//
//  ArticleDetailInteractor.swift
//  NewsAPI
//
//  Created by Andrey Nedov on 12/08/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailBusinessLogic
{
    func fetchArticle(request: ArticleDetail.FetchArticle.Request)
}

protocol ArticleDetailDataStore
{
    var article: DisplayedArticle? {get set}
}

class ArticleDetailInteractor: ArticleDetailBusinessLogic, ArticleDetailDataStore
{
    var presenter: ArticleDetailPresentationLogic?
    var worker: ArticleDetailWorker?
    
    
    var article: DisplayedArticle?
    // MARK: Do something
    
    func fetchArticle(request: ArticleDetail.FetchArticle.Request) {
        guard let article = article else { return }
        let responce = ArticleDetail.FetchArticle.Response(article: article)
        self.presenter?.presentArticle(response: responce)
    }
}

