//
//  ArticleDetailModels.swift
//  NewsAPI
//
//  Created by Andrey Nedov on 12/08/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ArticleDetail
{
    // MARK: Use cases
    
    enum FetchArticle
    {
        struct Request{}
        
        struct Response{
            let article: DisplayedArticle
        }
        struct ViewModel{
            struct Success {
                let displayedArticle: DisplayedArticle
            }
        }
    }
}

