//
//  ArticleDetailPresenter.swift
//  NewsAPI
//
//  Created by Andrey Nedov on 12/08/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailPresentationLogic
{
    func presentArticle(response: ArticleDetail.FetchArticle.Response)
}

class ArticleDetailPresenter: ArticleDetailPresentationLogic
{
    weak var viewController: ArticleDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentArticle(response: ArticleDetail.FetchArticle.Response)
    {
        let viewModel = ArticleDetail.FetchArticle.ViewModel.Success(displayedArticle: response.article)
        viewController?.displayArticle(viewModel: viewModel)
    }
}

