//
//  NewsListInteractor.swift
//  NewsAPI
//
//  Created by Andrey Nedov on 12/08/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListBusinessLogic
{
    func fetchNews(request: NewsList.FetchNews.Request)
    func selectArticle(request: NewsList.SelectArticle.Request)
}

protocol NewsListDataStore
{
    var article: DisplayedArticle? {get set}
    var updateFlag: Bool  {get set}
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore
{
    
    var article: DisplayedArticle?
    var updateFlag: Bool = false
    
    var presenter: NewsListPresentationLogic?
    private var apiWorker: NewsListWorker = NewsListWorker(service: APIService())
    
    func fetchNews(request: NewsList.FetchNews.Request) {
        updateFlag = request.refresh
        apiWorker.getNews { (result) in
            let responce = NewsList.FetchNews.Response(result: result, update: self.updateFlag)
            self.presenter?.presentNews(response: responce)
        }
    }
    
    func selectArticle(request: NewsList.SelectArticle.Request) {
        article = request.article
    }

}

