//
//  NewsListRouter.swift
//  NewsAPI
//
//  Created by Andrey Nedov on 12/08/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsListRoutingLogic
{
    func routeToDetails()
}

protocol NewsListDataPassing
{
  var dataStore: NewsListDataStore? { get }
}

class NewsListRouter: NSObject, NewsListRoutingLogic, NewsListDataPassing
{
  weak var viewController: NewsListViewController?
  var dataStore: NewsListDataStore?
  
    // MARK: Routing
    
    func routeToDetails() {
        let destination: ArticleDetailViewController = ArticleDetailViewController.fromStoryboard()
        guard let source = viewController,
            let sourceDataStore = dataStore,
            var destinationDataStore = destination.router?.dataStore else {
                assertionFailure("Could not instantiate required variables for routing")
                return
        }
        passDataToDetails(source: sourceDataStore, destination: &destinationDataStore)
        navigateToDetails(source: source, destination: destination)
    }
    
    //   MARK: Navigation
    
    private func navigateToDetails(source: UIViewController?, destination: UIViewController) {
        source?.navigationController?.pushViewController(destination, animated: true)
    }
    
    //   MARK: Passing data
    
    private func passDataToDetails(
        source: NewsListDataStore,
        destination: inout ArticleDetailDataStore
        ) {
        destination.article = source.article
    }
}
